#! /usr/bin/env python3
"""Generate the explicitly unrolled real solid harmonic evaluation in
src/Numerics/SoaSphericalTensor.h -- the SHEval0..SHEval<LMAX> family and the
SHEval dispatch function.

This implements the code generation scheme of

  Sloan, P., Efficient Spherical Harmonic Evaluation,
  Journal of Computer Graphics Techniques, vol. 2, no. 2, 84-90, 2013.

with one generalization the paper does not cover.  The paper evaluates on the
unit sphere, so its supplemental generator emits a bare constant wherever a
power of r^2 would go, and cannot produce this code as it stands.  QMCPACK's
basis needs the homogeneous solid harmonics r^l Y_lm, so every such term is
emitted as a multiple of fR2 instead and each SHEval function is a homogeneous
polynomial of degree Lmax.

Usage
  gen_sheval.py            check that SoaSphericalTensor.h matches this generator
  gen_sheval.py --write    rewrite the generated block in SoaSphericalTensor.h
  gen_sheval.py --tests    rewrite the generated unit test, tests/test_sheval.cpp
  gen_sheval.py --verify N validate the emitted code against SymPy's Ynm

On the constants.  Sloan notes that a naive evaluation of K(l,m) loses accuracy
at high l and recommends arbitrary precision, so every coefficient here is
evaluated exactly with mpmath and rounded exactly once, on print, to the
shortest decimal that round-trips to the intended double.

The literals committed to SoaSphericalTensor.h were printed by the original C++
generator, which computed them in long double and printed 32 significant digits.
A C++ floating literal with no suffix has type double, so everything past the
17th digit is discarded by the compiler and the two forms are the same number:
--check therefore compares constants as IEEE-754 doubles rather than as text,
and reports 2682 of 2682 identical.  Running --write reflows those literals to
their shortest round-tripping form; the compiled result is unchanged.
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

from mpmath import mp, mpf, pi, sqrt

# Highest angular momentum to unroll.  SHEval has no case beyond this.
LMAX = 19

# mpmath working precision.  Well beyond double; coefficients round once, on print.
mp.prec = 300

BEGIN = "// ---- BEGIN generated by src/Numerics/codegen/gen_sheval.py -- DO NOT EDIT ----"
END = "// ---- END generated by src/Numerics/codegen/gen_sheval.py ----"


# --------------------------------------------------------------- coefficients

def index(l, m):
    """Storage index for a real solid harmonic: i = l(l+1) + m."""
    return l * (l + 1) + m


def normalization(l, m):
    """K(l,m) = sqrt((2l+1)(l-|m|)! / (4 pi (l+|m|)!)); Listing 1 of the paper.

    The factorials are taken as a ratio so that neither one overflows on its own.
    """
    ratio = mpf(1)
    for k in range(l + abs(m), l - abs(m), -1):
        ratio *= k
    return sqrt((2 * mpf(l) + 1) / (4 * pi * ratio))


def prefactor(l, m):
    """The sqrt(2) K(l,m) prefactor of Eq. (1).  The sqrt(2) is absent for m = 0."""
    return sqrt(mpf(2)) * normalization(l, m) if m else normalization(l, m)


def diagonal(m):
    """Eq. (4a): P_m^m = (1-2m) P_{m-1}^{m-1}, with sin^m(theta) factored out.

    Factoring out sin^m(theta) is Snyder's trick: it leaves a polynomial in z,
    and the sin^m(theta) is absorbed into the (x, y) tower built by the
    trigonometric addition theorem.
    """
    value = mpf(1)
    for k in range(1, m + 1):
        value *= 1 - 2 * k
    return value


def coefficients(l, m):
    """Constants emitted for the (l, m) term, in source order.

    The shape depends only on l - m and follows the paper's recurrences:

      l - m == 0   Eq. (4a)   c
      l - m == 1   Eq. (4b)   c z
      l - m == 2   Eq. (4d)   a z^2 + b r^2
      l - m == 3   Eq. (4e)   z (a z^2 + b r^2)
      l - m >= 4   Eq. (4c)   A z P_{l-1}^m + B r^2 P_{l-2}^m

    Equations (4d) and (4e) are (4c) with (4a) and (4b) substituted in and the
    constants folded, which is what lets the first four terms of each tower be
    emitted without referring back to anything.

    The l - m >= 4 coefficients absorb the ratio of normalizations, because the
    terms they refer back to already carry their own K.
    """
    d, pre, diag = l - m, prefactor(l, m), diagonal(m)
    if d == 0:
        return [pre * diag]
    if d == 1:
        return [pre * (2 * m + 1) * diag]
    if d == 2:
        return [pre * (2 * m + 3) * (2 * m + 1) * diag / 2,
                -pre * (2 * m + 1) * diag / 2]
    if d == 3:
        return [pre * (2 * m + 5) * (2 * m + 3) * (2 * m + 1) * diag / 6,
                -pre * 3 * (4 * m * m + 8 * m + 3) * diag / 6]
    return [sqrt(mpf((2 * l + 1) * (2 * l - 1)) / mpf((l + m) * (l - m))),
            -sqrt(mpf((2 * l + 1) * (l + m - 1) * (l - m - 1))
                  / mpf((2 * l - 3) * (l + m) * (l - m)))]


def literal(value):
    """Shortest decimal string that round-trips to the intended double."""
    text = repr(float(mp.mpf(value)))
    return text[:-2] if text.endswith(".0") else text


# ------------------------------------------------------------- code emission

def temp_name(l, m, lmax):
    """Scratch variable holding the (l, m) coefficient.

    Cycles fTmpA/B/C with l - m so that the two terms a recurrence step reads are
    still live.  The final band (m == lmax) is a single term consumed
    immediately, and the generator this replaces emitted it on a different
    letter; that is reproduced here so the output matches.  Any letter is correct.
    """
    if m == lmax:
        return "fTmpB" if lmax == 1 else "fTmpC"
    return "fTmp" + "ABC"[(l - m) % 3]


def expression(l, m, previous, second_previous):
    """Right-hand side for the (l, m) coefficient."""
    d = l - m
    c = [literal(v) for v in coefficients(l, m)]
    if d == 0:
        return c[0]
    if d == 1:
        return f"{c[0]} * fZ"
    if d == 2:
        return f"{c[0]} * fZ2 + {c[1]} * fR2"
    if d == 3:
        return f"fZ * ({c[0]} * fZ2 + {c[1]} * fR2)"
    return f"{c[0]} * fZ * {previous} + {c[1]} * {second_previous} * fR2"


def sheval(lmax):
    """Emit SHEval<lmax>."""
    out = [f"// Lmax == {lmax}",
           "template<typename T>",
           f"void SHEval{lmax}(const T fX, const T fY, const T fZ, T* pSH)",
           "{",
           "  T fC0, fC1, fS0, fS1, fTmpA, fTmpB, fTmpC;"]
    if lmax >= 2:
        out.append("  T fZ2 = fZ * fZ;")
        out.append("  T fR2 = fX * fX + fY * fY + fZ * fZ;")
    else:
        out.append("")

    # m == 0 has no (x, y) dependence, so it is written straight into pSH and the
    # recurrence reads back out of pSH rather than out of a scratch variable.
    for l in range(lmax + 1):
        rhs = expression(l, 0, f"pSH[{index(l - 1, 0)}]", f"pSH[{index(l - 2, 0)}]")
        out.append(f"  pSH[{index(l, 0)}] = {rhs};")
    out.append("  fC0 = fX;")
    out.append("  fS0 = fY;")

    # m >= 1: one coefficient tower per m, paired with Re/Im (x + iy)^m.
    for m in range(1, lmax + 1):
        out.append("")
        cos_name, sin_name = f"fC{(m - 1) % 2}", f"fS{(m - 1) % 2}"
        for l in range(m, lmax + 1):
            name = temp_name(l, m, lmax)
            rhs = expression(l, m, temp_name(l - 1, m, lmax), temp_name(l - 2, m, lmax))
            out.append(f"  {name} = {rhs};")
            out.append(f"  pSH[{index(l, m)}] = {name} * {cos_name};")
            out.append(f"  pSH[{index(l, -m)}] = {name} * {sin_name};")
        if m < lmax:
            out.append(f"  fC{m % 2} = fX * {cos_name} - fY * {sin_name};")
            out.append(f"  fS{m % 2} = fX * {sin_name} + fY * {cos_name};")
    out.append("}")
    return "\n".join(out)


def dispatch(lmax):
    """Emit the SHEval dispatch function."""
    out = ["// auxiliary function",
           "template<typename T>",
           "void SHEval(const T fX0, const T fY0, const T fZ, T* pSH, const int l_max, bool addsign)",
           "{",
           "  T fX, fY;",
           "  if (addsign)",
           "  {",
           "    fX = -1.0L * fX0;",
           "    fY = -1.0L * fY0;",
           "  }",
           "  else",
           "  {",
           "    fX = fX0;",
           "    fY = fY0;",
           "  }",
           "  switch (l_max)",
           "  {"]
    for l in range(lmax + 1):
        if l:
            out.append("")
        out.append(f"  case {l}:")
        out.append(f"    SHEval{l}(fX, fY, fZ, pSH);")
        out.append("    break;")
    out.append("  }")
    out.append("}")
    return "\n".join(out)


def generated_block():
    """The whole generated region, without the markers."""
    header = ["// Explicitly unrolled functions based on:",
              "// Sloan, P., Efficient Spherical Harmonic Evaluation, Journal of Computer "
              "Graphics Techniques, vol. 2, no. 2, 84-90, 2013"]
    body = [sheval(l) for l in range(LMAX + 1)] + [dispatch(LMAX)]
    return "\n".join(header) + "\n" + "\n\n".join(body)


# ------------------------------------------------------------------ file I/O

def header_path():
    return Path(__file__).resolve().parent.parent / "SoaSphericalTensor.h"


def style_path():
    """QMCPACK's clang-format configuration, src/.clang-format."""
    return Path(__file__).resolve().parent.parent.parent / ".clang-format"


def clang_format(text):
    """Run clang-format over a standalone fragment.

    The generated block is formatted on its own rather than by reformatting the
    whole header, so that a clang-format version newer than the one the rest of
    the file was written with does not churn unrelated lines.  The style file is
    named explicitly because clang-format otherwise searches upward from the
    input file, which finds nothing in a temporary directory.
    """
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        fragment = Path(tmp) / "fragment.h"
        fragment.write_text(text, encoding="utf-8")
        subprocess.run(["clang-format", f"--style=file:{style_path()}", "-i", str(fragment)],
                       check=True)
        return fragment.read_text()


def splice(text, block):
    """Replace the marked region of the header with block."""
    start, end = text.index(BEGIN), text.index(END)
    return text[:start] + BEGIN + "\n" + block + text[end:]


def rendered():
    """The generated region, formatted, as it should appear in the header."""
    return clang_format(generated_block())


def write():
    path = header_path()
    path.write_text(splice(path.read_text(), rendered()), encoding="utf-8")
    print(f"wrote {path}")


NUMBER = re.compile(r"-?\d+\.\d+(?:[eE][-+]?\d+)?")


def check():
    """Compare the header on disk against a fresh generation.

    Constants are compared as doubles rather than as text, so a header whose
    literals were printed by a different generator still passes as long as every
    one of them parses to the same double.
    """
    import struct

    text = header_path().read_text()
    have = text[text.index(BEGIN) + len(BEGIN):text.index(END)].strip("\n").splitlines()
    want = rendered().strip("\n").splitlines()

    if len(have) != len(want):
        sys.exit(f"line count differs: {len(have)} on disk vs {len(want)} generated")

    constants = 0
    for n, (a, b) in enumerate(zip(have, want), 1):
        if NUMBER.sub("K", a) != NUMBER.sub("K", b):
            sys.exit(f"line {n} of the generated block differs:\n  on disk   {a}\n  generated {b}")
        for i, j in zip(NUMBER.findall(a), NUMBER.findall(b)):
            if struct.pack("<d", float(i)) != struct.pack("<d", float(j)):
                sys.exit(f"line {n}: {i} and {j} are different doubles")
            constants += 1
    print(f"identical: {len(have)} lines, {constants} constants equal as doubles")


TEST_TEMPLATE = r'''//////////////////////////////////////////////////////////////////////////////////////
// This file is distributed under the University of Illinois/NCSA Open Source License.
// See LICENSE file in top directory for details.
//
// Copyright (c) 2026 QMCPACK developers.
//
// File developed by: Shiv Upadhyay, shivnupadhyay@gmail.com, University of Washington
//
// File created by: Shiv Upadhyay, shivnupadhyay@gmail.com, University of Washington
//////////////////////////////////////////////////////////////////////////////////////

// ---- AUTOMATICALLY GENERATED BY src/Numerics/codegen/gen_sheval.py -- DO NOT EDIT ----
//
// Regenerate with
//     src/Numerics/codegen/gen_sheval.py --tests
//
// Covers every SHEval0..SHEval%LMAX function and both branches of the SHEval
// dispatch.  The reference values are r^l S_l^m evaluated from mpmath's
// spherical harmonic in extended precision and rounded once to double, so this
// checks the unrolled code against an independent definition rather than
// against the recurrences it was generated from.

#include "catch.hpp"

#include "Message/Communicate.h"
#include "Numerics/SoaSphericalTensor.h"

#include <cmath>

namespace qmcplusplus
{
namespace
{
constexpr int sheval_lmax    = %LMAX;
constexpr int sheval_size    = (sheval_lmax + 1) * (sheval_lmax + 1);
constexpr int sheval_npoints = %NPOINTS;

constexpr double sheval_epsilon = %EPSILON;
constexpr double sheval_margin  = %MARGIN;

// clang-format off
const double sheval_points[sheval_npoints][3] = %POINTS;

const double sheval_reference[sheval_npoints][sheval_size] = %VALUES;
// clang-format on

/// (-1)^m for the storage index l*(l+1)+m, the factor the addsign convention adds
inline double condon_shortley(int idx)
{
  const int l = static_cast<int>(std::sqrt(static_cast<double>(idx)));
  const int m = idx - l * (l + 1);
  return (m % 2 == 0) ? 1.0 : -1.0;
}
} // namespace

TEST_CASE("SoaSphericalTensor SHEval", "[numerics]")
{
  for (int p = 0; p < sheval_npoints; p++)
  {
    const double x = sheval_points[p][0];
    const double y = sheval_points[p][1];
    const double z = sheval_points[p][2];

    for (int l_max = 0; l_max <= sheval_lmax; l_max++)
    {
      SoaSphericalTensor<double> st(l_max);
      st.evaluateV(x, y, z);
      const double* Ylm = st[0];

      for (int i = 0; i < (l_max + 1) * (l_max + 1); i++)
      {
        INFO("point " << p << ", l_max " << l_max << ", index " << i);
        CHECK(Ylm[i] == Approx(sheval_reference[p][i]).epsilon(sheval_epsilon).margin(sheval_margin));
      }
    }
  }
}

TEST_CASE("SoaSphericalTensor SHEval addsign", "[numerics]")
{
  for (int p = 0; p < sheval_npoints; p++)
  {
    const double x = sheval_points[p][0];
    const double y = sheval_points[p][1];
    const double z = sheval_points[p][2];

    for (int l_max = 0; l_max <= sheval_lmax; l_max++)
    {
      SoaSphericalTensor<double> st(l_max, true);
      st.evaluateV(x, y, z);
      const double* Ylm = st[0];

      for (int i = 0; i < (l_max + 1) * (l_max + 1); i++)
      {
        const double expected = condon_shortley(i) * sheval_reference[p][i];
        INFO("point " << p << ", l_max " << l_max << ", index " << i);
        CHECK(Ylm[i] == Approx(expected).epsilon(sheval_epsilon).margin(sheval_margin));
      }
    }
  }
}

} // namespace qmcplusplus
'''


# --------------------------------------------------------------- unit tests

# Four points: the z axis, where every m != 0 term vanishes identically, the
# point the hand-written tensor tests already use, and two off-axis points with
# no symmetry.  One reference table covers every (l, m) up to LMAX, and SHEval<n>
# is checked against its first (n+1)^2 entries, so the twenty functions are also
# checked for consistency with one another.
TEST_POINTS = ((0.0, 0.0, 1.0),
               (1.3, 1.2, -0.5),
               (-0.52854, -1.04749, 0.45281),
               (-1.32601, 0.02232, -1.38753))

# The recurrence chain loses about a digit per few bands; the measured worst
# case at LMAX == 19 is 1e-13 relative, so this leaves two orders of headroom
# for a compiler that contracts differently.
TEST_EPSILON = 1e-11
TEST_MARGIN = 1e-11


def tests_path():
    return Path(__file__).resolve().parent.parent / "tests" / "test_sheval.cpp"


def reference_value(l, m, point):
    """r^l S_l^m at point, in the addsign == false convention.

    Built from mpmath's spherical harmonic rather than from the recurrences this
    script emits, so the generated code is checked against an independent
    definition and not against itself.
    """
    from mpmath import acos, atan2, spherharm

    x, y, z = (mpf(c) for c in point)
    r = sqrt(x * x + y * y + z * z)
    value = spherharm(l, abs(m), acos(z / r), atan2(y, x))
    if m == 0:
        angular = value.real
    else:
        angular = sqrt(mpf(2)) * (value.real if m > 0 else value.imag)
    return angular * r**l


def reference_table():
    """One row of (LMAX + 1)^2 values per test point, in storage order."""
    return [[reference_value(l, m, point)
             for l in range(LMAX + 1) for m in range(-l, l + 1)]
            for point in TEST_POINTS]


def table(rows, per_line=4):
    """A brace-enclosed C++ initializer for a two-dimensional double array."""
    out = []
    for i, row in enumerate(rows):
        literals = [literal(v) for v in row]
        chunks = [", ".join(literals[j:j + per_line]) for j in range(0, len(literals), per_line)]
        body = (",\n" + " " * 5).join(chunks)
        out.append("    {" + body + "}" + ("," if i + 1 < len(rows) else ""))
    return "{\n" + "\n".join(out) + "}"


def test_source():
    """The complete generated unit test."""
    values = reference_table()
    return (TEST_TEMPLATE
            .replace("%LMAX", str(LMAX))
            .replace("%NPOINTS", str(len(TEST_POINTS)))
            .replace("%EPSILON", repr(TEST_EPSILON))
            .replace("%MARGIN", repr(TEST_MARGIN))
            .replace("%POINTS", table([list(p) for p in TEST_POINTS], per_line=3))
            .replace("%VALUES", table(values)))


def write_tests():
    path = tests_path()
    path.write_text(clang_format(test_source()), encoding="utf-8")
    print(f"wrote {path} ({len(TEST_POINTS)} points, {(LMAX + 1) ** 2} terms each)")


def check_tests():
    path = tests_path()
    if not path.exists():
        return
    if path.read_text(encoding="utf-8") != clang_format(test_source()):
        sys.exit(f"{path} is stale; regenerate with gen_sheval.py --tests")
    print(f"identical: {path.name}")


# ---------------------------------------------------------------- validation

def verify(lmax=6, points=200, tolerance=1e-11):
    """Check the emitted code against SymPy's spherical harmonics.

    The generated statements are translated to Python and evaluated in double
    precision, and compared against r^l times the real spherical harmonic built
    from SymPy's Ynm, evaluated at 50 digits.  This validates the generated
    source itself -- its constants, its statement order and its indexing -- and
    not merely the recurrences it was produced from.

    The residual is the double-precision round-off of the recurrence chain, so
    the comparison is numerical; it grows slowly with lmax.
    """
    import random

    from mpmath import mpf, nstr
    from sympy import (Integer, Symbol, cos, expand, expand_complex, expand_func,
                       expand_trig, lambdify, powdenest, simplify, sin)
    from sympy import im as sympy_im, re as sympy_re, sqrt as sympy_sqrt

    x, y, z = (Symbol(s, real=True) for s in "xyz")
    r, rho = Symbol("r", positive=True), Symbol("rho", positive=True)
    theta, phi = Symbol("theta", real=True), Symbol("phi", real=True)

    def reference(l, m):
        """r^l S_l^m, without the (-1)^m the generated code leaves out."""
        if m == 0:
            angular = expand_func(Ynm(l, 0, theta, phi))
        else:
            full = expand_complex(expand_func(Ynm(l, abs(m), theta, phi)))
            angular = sympy_sqrt(2) * (sympy_re(full) if m > 0 else sympy_im(full))
        e = expand(expand_trig(angular) * r**l)
        e = e.subs({cos(phi): x / rho, sin(phi): y / rho,
                    cos(theta): z / r, sin(theta): rho / r}, simultaneous=True)
        e = expand(e).subs(rho**2, x**2 + y**2).subs(r**2, x**2 + y**2 + z**2)
        e = powdenest(e, force=True)
        return expand(simplify(e.subs(rho, sympy_sqrt(x**2 + y**2))
                               .subs(r, sympy_sqrt(x**2 + y**2 + z**2))))

    from sympy.functions.special.spherical_harmonics import Ynm

    # translate the emitted C++ into a Python function evaluated in float64
    body = []
    for line in sheval(lmax).splitlines():
        s = line.strip().rstrip(";")
        if not s or s.startswith(("//", "template", "void", "{", "}")):
            continue
        s = re.sub(r"^T\s+", "", s)
        if " = " not in s:            # the scratch-variable declaration
            continue
        body.append("    " + s)
    source = (f"def evaluate(fX, fY, fZ):\n"
              f"    pSH = [0.0] * {(lmax + 1) ** 2}\n" + "\n".join(body) + "\n    return pSH\n")
    namespace = {}
    exec(source, namespace)
    evaluate = namespace["evaluate"]

    exact = {(l, m): lambdify((x, y, z), reference(l, m), "mpmath")
             for l in range(lmax + 1) for m in range(-l, l + 1)}

    random.seed(0)
    worst, where = 0.0, None
    for _ in range(points):
        px, py, pz = (random.uniform(-1.5, 1.5) for _ in range(3))
        emitted = evaluate(px, py, pz)
        for (l, m), fn in exact.items():
            want = fn(mpf(px), mpf(py), mpf(pz))
            error = abs(mpf(emitted[index(l, m)]) - want) / max(abs(want), mpf(1))
            if error > worst:
                worst, where = error, (l, m)
    print(f"SHEval{lmax}: {(lmax + 1) ** 2} terms, {points} points, "
          f"max relative error {nstr(worst, 3)} (worst at l={where[0]} m={where[1]})")
    if worst > tolerance:
        sys.exit(f"exceeds tolerance {tolerance}")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--write", action="store_true",
                        help="rewrite the generated block in SoaSphericalTensor.h")
    parser.add_argument("--tests", action="store_true",
                        help="rewrite the generated unit test in tests/test_sheval.cpp")
    parser.add_argument("--verify", type=int, nargs="?", const=6, metavar="LMAX",
                        help="validate the emitted code against SymPy (default lmax 6)")
    args = parser.parse_args()
    if args.verify is not None:
        verify(args.verify)
    elif args.write:
        write()
    elif args.tests:
        write_tests()
    else:
        check()
        check_tests()


if __name__ == "__main__":
    main()
